### ISSUE TITLE
`BoundedEncodedLen` tracking issue

### ISSUE THREAD

**Issue by coriolinus** [paritytech/parity-scale-codec#266]
## Rationale

For PoV benchmarking, we need some way to estimate what the maximum encoded size of an arbitrary storage item can be. We've settled on a new trait, `BoundedEncodedLen`. 

While [`Encode::size_hint`](https://substrate.dev/rustdocs/v3.0.0/parity_scale_codec/trait.Encode.html#method.size_hint) already exists, we can't rely on it. One fatal flaw: it's an optional, "if possible" method which for many structs simply returns the default size of `0`. Another: `Encode` is implemented for certain types such as `VecDeque<T>`, which we'd want to intentionally exclude from storage, as they aren't bounded. We need a trait which we can use to exclude types.

## Design

```rust
pub trait BoundedEncodedLen: Encode {
  fn max_encoded_len() -> usize;
}
```

## Roadmap

- [ ] Introduce the `BoundedEncodedLen` trait to SCALE
- [ ] Implement for primitive types, fixed size arrays, tuples, etc. Non-containers for which `Encode` is implemented. Mostly defers to `sp_std::mem::size_of::<T>()`.
- [ ] Implement for `BoundedVec<T>`
- [ ] Implement for certain containers:
  - [ ] `Option<T>`
  - [ ] `Result<T, E>`
  - [ ] `PhantomData<T>`
- [ ] **Optional**: Implement `Bounded` variants for other container types for which `Encode` is implemented. Implement `BoundedEncodedLen` for these bounded variants.
  - [ ] `BTreeMap<K, V>`
  - [ ] `BTreeSet<T>`
  - [ ] `BinaryHeap<T>`
  - [ ] `LinkedList<T>`
  - [ ] `VecDeque<T>`
- [ ] Derive macro: `#[derive(Encode, BoundedEncodedLen)]` for non-container structs, enums. Requires all fields to implement `Encode` and `BoundedEncodedLen`.
- [ ] Extend FRAME storage macros such that all `StorageMap` and friends are actually implemented as newtypes which implement the full API of the parent type, plus `BoundedEncodedLen`
  - [ ] Backwards-compatibility: existing macro declarations should use a fixed bound of 300,000
  - [ ] A new optional attribute (pending bikeshedding) allows per-map customization of bound. `#[storage::map_bound(300_000)]`. The value specified in this attribute is used to determine the bounded length of the map. 
- [ ] New requirement on `frame::storage`: all storage items must implement `BoundedEncodedLen`.
- [ ] Patch all the holes to make everything work.

## Notes

This always explicitly computes an upper bound. While a `u128` can potentially be compact-encoded in only one byte, `u128::max_encoded_len()` will always return 16.

While implementations of `BoundedVec<T>` and friends impose a hard cap on their length, we do _not_ use `BoundedEncodedLen` to impose a hard cap on the size of `StorageMap` and friends. While potentially a parachain author could misrepresent the bounds on its maps to attempt to pack a parachain block with more transactions, that behavior is self-defeating. Eventually they will try to pack too many transactions into a block, causing that block to become invalid because its actual size is too large. User documentation for the `storage::map_bound` attribute should emphasize that it is in the chain author's best interest to use a reasonable value here.

We'd like to offer logging warnings that could be noted by Prometheus etc when the size of `StorageMap` exceeds certain thresholds (eg. info at 80%, warn at 100%), but that feature is out of scope of this tracking issue. It requires additional design work because currently the only way to determine a map's size is to iterate over its members, which is not performant.

**Comment by bkchr** [comment]
>     * Introduce the `BoundedEncodedLen` trait to SCALE

Why? Why should this exist in scale-codec?


What I still don't understand, how should this help to calculate the proof size? The proof size is not only composed of the size of the individual elements. The size also comes from the trie structure itself that is encoded in the proof. Than there are also values included which are may not being accessed by an extrinsic and still would increase the proof size.

**Comment by shawntabrizi** [comment]
After our chat in Element, I agree this probably can go in Substrate instead of SCALE.
